name: Start tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          venv/scripts/activate

      - name: Install dependencies
        run: pip install -r .\task1\requirements.txt

      - name: Run tests with pytest
        run: |
          pip install pytest-cov
          pytest --cov=.\task1\test_solve_quadratic_equation.py

      - name: Upload coverage report to Coveralls
        run: |
          pip install coveralls
          coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
